### ISSUE TITLE
Fail with Redmine 3.x

### ISSUE THREAD

**Issue by topkool** [martin-denizet/redmine_login_audit#11]
The plugin crashes when loging with Redmine 3.0.1

**Comment by martin-denizet** [comment]
Ok thanks, will check.

**Comment by jonvargas** [comment]
Is it supported on 3.1?

**Comment by martin-denizet** [comment]
Hello, I've an updated version that I didn't publish yet because I need to apply licensing correctly first. Will do it quickly, stay tuned.

**Comment by jonvargas** [comment]
Thank you so much Martin, I'll keep suscribed to updates.

**Comment by dgutkowsky** [comment]
Hi, any news on Redmine 3.x support? :)

**Comment by martin-denizet** [comment]
I worked on it today. It's not ready yet. However it should ship tomorrow!

**Comment by martin-denizet** [comment]
Hooray! Version 0.2.0 released!
Feedback welcome.
