### ISSUE TITLE
please add copyright attribution

### ISSUE THREAD

**Issue by onlyjob** [martin-denizet/redmine_login_audit#14]
Similar to custom_css this plugin needs proper copyright statement like

    Copyright 2013-2014 Martin DENIZET <martin.denizet@supinfo.com>

It would be sufficient to add it to readme, ideally accompanied by license notice.
Thanks.

**Comment by martin-denizet** [comment]
Should be fixed with version 0.2.0.
Thanks!

**Comment by onlyjob** [comment]
Unfortunately license is __non-free__ because it does not comply with 
_ §5. No Discrimination Against Persons or Groups_ of the [open source definition](http://opensource.org/osd.html). It is also DFSG-incompatible which means that "redmine_login_audit" can't be accepted to Debian. :-(

**Comment by onlyjob** [comment]
Perhaps it would be better to use strong copyleft license (e.g. GPL-3 or AGPL-3) instead of using discriminatory clause on top of permissive _Expat_ (aka _MIT_) license. The problem is that the following clause do not qualify for free (i.e. open source) software:

> The Software shall not be used nor made available to TESTTailor or any
    individual or organization related or operated by Adarsh Mehta from
    Germany; some people just don't deserve free work to be made available
    to them.

I recommend to switch to unmodified (A)GPL-3 license -- I believe it is strong enough to restrict offenders from wrongdoings.
