### ISSUE TITLE
hmm.. 

### ISSUE THREAD

**Issue by alexyang12** [martin-denizet/redmine_login_audit#16]
finished migration.. but 

what is this ?  on 3.1.1 stable 

Completed 500 Internal Server Error in 0ms (ActiveRecord: 0.0ms)

NoMethodError (undefined method `initialize_grid' for #<LoginAuditController:0x8da5ff0>):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by martin-denizet** [comment]
Hello,
Did the bundle install work correctly?
The plugin requires wice_grid gem.
Cheers,

**Comment by scar2yjs** [comment]
\htdocs  >  bundle list

the git source https://github.com/ ~~~~~~~~~   is not yet checked out. plz run bundle install ' 

\redmine_login_audit  > bundle list 

* wice_grid <3.5.0>    

why different?  @_@

**Comment by martin-denizet** [comment]
The plugin has its own Gemfile: https://github.com/martin-denizet/redmine_login_audit/blob/master/Gemfile
Is that what's bothering you? I need to update the README to reflect this change.

**Comment by scar2yjs** [comment]
can not enter login_audit page : (

**Comment by martin-denizet** [comment]
Please update to version 0.2.2. You will need to run the ```bundle install``` again.

**Comment by yatkha** [comment]
Hi, Martin

Redmine 3.2.1 stable from Bitnami, Plugin 0.2.4
and the same situation here, migration OK, but:

```
Completed 500 Internal Server Error in 27ms (ActiveRecord: 8.0ms)
NoMethodError (undefined method `initialize_grid' for #<LoginAuditController:0x007f59661748e8>):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```
`/opt/bitnami/apps/redmine/htdocs$  bundle list`
lack of wice_grid, therubyracer gems

`/opt/bitnami/apps/redmine/htdocs/plugins/redmine_login_audit$ bundle list`
  * therubyracer (0.12.2)
  * wice_grid (3.5.0)

How to fix it?
