### ISSUE TITLE
search by firstname or lastname

### ISSUE THREAD

**Issue by mmaker86** [martin-denizet/redmine_login_audit#17]
Hi,
Doesn't work search by firstname or lastname after upgrade to latest version of login_audit: 

Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

 Unknown column 'users.firstname' in 'where clause': SELECT COUNT(count_column) FROM (SELECT  1 AS count_column FROM `login_audits` WHERE ((   users.firstname LIKE '%resr%')) LIMIT 50 OFFSET 0) subquery_for_count

**Comment by martin-denizet** [comment]
Thanks, will check it out!

**Comment by mmaker86** [comment]
Hi,
is there any news about issue?

**Comment by martin-denizet** [comment]
Please update to version 0.2.2, that should do it.
Note that you will need to run the ```bundle install``` again.
