### ISSUE TITLE
Config not saved

### ISSUE THREAD

**Issue by MattMuffin** [martin-denizet/redmine_login_audit#30]
Hello,

I m using RM v3.3.1 and when I change something in the config page of this plugin, such as "log: successes" and then save, the banner message indicates that the save was successful but the config page still displays default values.

here is the log from redmine:

Started POST "/settings/plugin/redmine_login_audit" for x.x.x.x at 2016-10-21 15:52:20
Processing by SettingsController#plugin as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"Pt3fmCfHj12lErXJiTaxZJYNlxSkEqdq0PbiDpYFkTQTKp3JFy71rsI36x6Uev1AXyfY3OTXvILpp3vL01OqWg==", "settings"=>{"log_setting"=>"1", "audit_rows_per_page"=>""}, "commit"=>"Appliquer", "id"=>"redmine_login_audit"}
  Current user: matt (id=1)
Redirected to https://redmine.xxx.com/settings/plugin/redmine_login_audit
Completed 302 Found in 80ms (ActiveRecord: 75.3ms)
Started GET "/settings/plugin/redmine_login_audit" for x.x.x.x at 2016-10-21 15:52:20
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_login_audit"}
Settings cache cleared.
  Current user: mo (id=1)
  Rendered plugins/redmine_login_audit/app/views/settings/_login_audit.html.erb (0.8ms)
  Rendered settings/plugin.html.erb within layouts/admin (1.5ms)
  Rendered admin/_menu.html.erb (2.2ms)
  Rendered inline template (0.3ms)
  Rendered plugins/sidebar_hide/app/views/sidebar/_hideButton_partial.html.erb (0.2ms)
  Rendered layouts/base.html.erb (16.1ms)
Completed 200 OK in 63ms (Views: 19.0ms | ActiveRecord: 40.3ms)

**Comment by tolot27** [comment]
I do have the same problem. I get "log:success" but an additional yellow banner with "Logging is disabled, nothing is logged!" How to fix it?

There were no errors during rake run and the file permissions are correct.

**Comment by martin-denizet** [comment]
That should be fixed now. Sorry for the delay!
